@startuml class-task1

class Sorter{
    load()
    sort()
    getPlan()
}

class Line{
    Position[] positions

    put()
    get()
    toString()
    toArray()
}

class Position{
    Linable linable

    setLinable()
}

class Linable{
    setPosition()
    getPosition()
    getValue()
}

class Gourd{
    Position position

    getGourdByRank()
    rank()
    toString()
    setPosition()
    getPosition()
    swapPosition()
    getValue()
}

class Geezer{
    Geezer theGeezer
    Sorter sorter
    
    getTheGeezer()
    setSorter()
    lineUp()
    parsePlan()
    execute()
}

class BubbleSorter{
    int[] a
    String plan 
    
    load()
    swap()
    sort()
    getPlan()
}

@enduml